require_relative '../app/models/comedian.rb'
require_relative '../app/models/special.rb'
Special.destroy_all
Comedian.destroy_all
Comedian.create(name: "Chris D'Elia",  age: 38, birthplace: "Montclair, New Jersey", image_url: "https://upload.wikimedia.org/wikipedia/commons/4/4b/Chris_D%27Elia.jpg")
Comedian.create(name: "Dane Cook",  age: 46, birthplace: "Cambridge, Maine", image_url: "https://pixel.nymag.com/imgs/daily/vulture/2019/02/13/13-dane-cook.w330.h330.2x.jpg")
Comedian.create(name: "Louis C.K.",  age: 51, birthplace: "Washington, D.C.", image_url: "https://media1.fdncms.com/pittsburgh/imager/u/blog/13239255/louis_ck_kuwait_crop_cropped.jpg?cb=1548183367")
Comedian.create(name: "Joey Diaz",  age: 55, birthplace: "Havana, Cuba", image_url: "https://comedycentral.mtvnimages.com/images/ccstandup/comedians/800x600/JoeyDiaz_800x600.jpg?quality=0.91&width=320&height=320&crop=true")
Comedian.create(name: "Chad Daniels",  age: 43, birthplace: "Fergus Falls, MN", image_url: "https://www.rumorscomedyclub.com/wp-content/uploads/2016/09/Chad-2019-bio.jpg")
Comedian.create(name: "Kevin Hart",  age: 39, birthplace: "Philadelphia, PA", image_url: "http://www.philly.com/resizer/bHw4bvIexfBozzYo6gSgV1vpEXk=/1400x932/center/middle/arc-anglerfish-arc2-prod-pmn.s3.amazonaws.com/public/DBTWGCGWV5C7ZJBACNCBPOCUWE.jpg")
Comedian.create(name: "Dave Chappelle",  age: 45, birthplace: "Washington, D.C.", image_url: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTII3JGyHZiZx-tRsKYcDk8jotJ6kK6yGNiCof1mLfTw5DxekFZtg")
Comedian.create(name: "Chris Rock",  age: 53, birthplace: "Andrews, SC", image_url: "https://static.independent.co.uk/s3fs-public/thumbnails/image/2018/02/14/14/chris-rock-netflix.jpg?w968")
Comedian.create(name: "Tom Segura",  age: 39, birthplace: "Cincinnati, OH", image_url: "https://pixel.nymag.com/imgs/daily/vulture/2018/07/12/splitsider/879409292.w700.h467.2x.jpg")
Comedian.create(name: "Ari Shaffir",  age: 44, birthplace: "New York City, NY", image_url: "https://i2.wp.com/www.foodrepublic.com/wp-content/uploads/2016/02/Ari-Shaffir-TINH-1.jpg?resize=1400%2C2100")
Comedian.create(name: "Theo Von",  age: 38, birthplace: "Mandeville, LA", image_url: "https://uproxx.files.wordpress.com/2016/02/theo-von-no-offense-feature.jpg?quality=95")
Comedian.create(name: "Jerry Seinfeld",  age: 64, birthplace: "Brooklyn, NY", image_url: "https://www.gannett-cdn.com/-mm-/aec403ad632f33650ec1aa7926a673a5a6b987b8/c=420-0-2149-1300/local/-/media/2015/09/17/Westchester/Westchester/635780965457520146--ASBBrd-07-27-2012-PressMon-1-A002-2012-07-26-IMG-People-Seinfeld-7-1-4U1UD.jpg?width=534&height=401&fit=crop")

Special.create(title: "Man On Fire", duration_mins: 65, comedian_id: 1, image_url: "https://m.media-amazon.com/images/M/MV5BMDE3Y2RkZjMtNGYwNC00NjI5LWJkNzUtNjZlYmYyMmFhMTJlXkEyXkFqcGdeQXVyMTk2ODU0OTM@._V1_.jpg")
Special.create(title: "Incorrigible", duration_mins: 83, comedian_id: 1, image_url: "https://m.media-amazon.com/images/M/MV5BYTMwOTAxYTgtYTYwMi00YzMwLWFlMzAtNmUwNzdhMDNlNjhkXkEyXkFqcGdeQXVyMjIyMDAzNg@@._V1_SY1000_CR0,0,666,1000_AL_.jpg")
Special.create(title: "Vicious Circle", duration_mins: 90, comedian_id: 2, image_url: "https://m.media-amazon.com/images/M/MV5BMTgwNDkzNTk4MF5BMl5BanBnXkFtZTcwMzQ3NjgzMQ@@._V1_.jpg")
Special.create(title: "Isolated Incidient", duration_mins: 55, comedian_id: 2, image_url: "https://m.media-amazon.com/images/M/MV5BODE3OTM2OTg2MV5BMl5BanBnXkFtZTgwOTM0MzA2MDE@._V1_.jpg")
Special.create(title: "Rough Around The Edges", duration_mins: 65, comedian_id: 2, image_url: "https://m.media-amazon.com/images/M/MV5BMjM0ODQ2OTE3N15BMl5BanBnXkFtZTgwMDEzMjA2MDE@._V1_.jpg")
Special.create(title: "Oh My God", duration_mins: 58, comedian_id: 3, image_url: "https://m.media-amazon.com/images/M/MV5BMjQ4NjQwOTYzNl5BMl5BanBnXkFtZTcwNjU2NjczOQ@@._V1_.jpg")
Special.create(title: "Live At The Beacon Theater", duration_mins: 63, comedian_id: 3, image_url: "https://m.media-amazon.com/images/M/MV5BNzIxMTUxMjYzMV5BMl5BanBnXkFtZTcwMDYwMjE0Nw@@._V1_.jpg")
Special.create(title: "Hilarious", duration_mins: 88, comedian_id: 3, image_url: "https://m.media-amazon.com/images/M/MV5BNTQyODYyNzcxN15BMl5BanBnXkFtZTgwOTA3MzcwMzE@._V1_.jpg")
Special.create(title: "Sociably Unacceptable", duration_mins: 57, comedian_id: 4, image_url: "https://m.media-amazon.com/images/M/MV5BZTAxNTViYmUtYWU0OC00YTNhLTg3YTYtMTkwMjgzOTFkZGFmL2ltYWdlXkEyXkFqcGdeQXVyMzcwMjcwNQ@@._V1_SY1000_CR0,0,666,1000_AL_.jpg")
Special.create(title: "As Is", duration_mins: 52, comedian_id: 5, image_url: "https://m.media-amazon.com/images/M/MV5BODY2OWIxYzMtYjEwOS00ZjRiLWI3ZGEtMWFmYTQxOTFiY2E1L2ltYWdlXkEyXkFqcGdeQXVyNTM3MDMyMDQ@._V1_.jpg")
Special.create(title: "I'm A Grown Little Man", duration_mins: 73, comedian_id: 6, image_url: "https://m.media-amazon.com/images/M/MV5BMjI4MTYwNTUzMF5BMl5BanBnXkFtZTcwODk1Mjk3Mw@@._V1_.jpg")
Special.create(title: "Let Me Explain", duration_mins: 75, comedian_id: 6, image_url: "https://m.media-amazon.com/images/M/MV5BMTg4MjM2MjAxOF5BMl5BanBnXkFtZTcwMTAzOTEyOQ@@._V1_SY1000_CR0,0,673,1000_AL_.jpg")
Special.create(title: "What Now?", duration_mins: 96, comedian_id: 6, image_url: "https://m.media-amazon.com/images/M/MV5BNzI2MDk3OTA5N15BMl5BanBnXkFtZTgwMDU1MDgxMDI@._V1_SY1000_CR0,0,674,1000_AL_.jpg")
Special.create(title: "Equaniminity", duration_mins: 60, comedian_id: 7, image_url: "https://m.media-amazon.com/images/M/MV5BODJkMTAxNmYtZDg4OS00NzA2LTlmZTUtMDc2MjIwMzE4ZDMxXkEyXkFqcGdeQXVyMTk3NDAwMzI@._V1_.jpg")
Special.create(title: "Killin' Them Softly", duration_mins: 57, comedian_id: 7, image_url: "https://m.media-amazon.com/images/M/MV5BMTcyOGMxN2MtYzUwYy00YzQxLTgwZTItZjAxZTIzYWM1YzEyXkEyXkFqcGdeQXVyNjExODE1MDc@._V1_.jpg")
Special.create(title: "Kill The Messanger", duration_mins: 79, comedian_id: 8, image_url: "https://m.media-amazon.com/images/M/MV5BMjAwMjQxNDA5OF5BMl5BanBnXkFtZTcwNTE3MzM5MQ@@._V1_.jpg")
Special.create(title: "Bigger & Blacker", duration_mins: 65, comedian_id: 8, image_url: "https://m.media-amazon.com/images/M/MV5BODQzOWExYjktZDQ2OC00YTA5LWI3YzctMDFjNjc3ZTM5NTA0XkEyXkFqcGdeQXVyMTk3NDAwMzI@._V1_.jpg")
Special.create(title: "Never Scared", duration_mins: 80, comedian_id: 8, image_url: "https://m.media-amazon.com/images/M/MV5BMTlhYzMzNzItNWMyYy00ZGRlLWI1N2UtOGI2YjIwOGEwYTViXkEyXkFqcGdeQXVyMTk3NDAwMzI@._V1_SY1000_CR0,0,666,1000_AL_.jpg")
Special.create(title: "Mostly Stories", duration_mins: 73, comedian_id: 9, image_url: "https://m.media-amazon.com/images/M/MV5BZWE2Nzc5N2YtOWM0OS00ZWVmLThhOTctNjNlNGI0NTQzMTU5XkEyXkFqcGdeQXVyMzAzODY0NzE@._V1_.jpg")
Special.create(title: "Completely Normal", duration_mins: 74, comedian_id: 9, image_url: "https://m.media-amazon.com/images/M/MV5BMTcyODE0Mzk1Nl5BMl5BanBnXkFtZTgwMDk4ODE0NDE@._V1_.jpg")
Special.create(title: "Paid Regular", duration_mins: 73, comedian_id: 10, image_url: "https://m.media-amazon.com/images/M/MV5BMjBlMGE4ZWUtZmExOC00NzcxLWFkMjMtNDYwMzczOGQ0NzRlXkEyXkFqcGdeQXVyNTMxMjgxMzA@._V1_.jpg")
Special.create(title: "Passive Aggressive", duration_mins: 60, comedian_id: 10, image_url: "https://m.media-amazon.com/images/M/MV5BMTYzNDUyMjE4M15BMl5BanBnXkFtZTcwMTQ3NzQxOQ@@._V1_SY1000_CR0,0,647,1000_AL_.jpg")
Special.create(title: "No Offense", duration_mins: 66, comedian_id: 11, image_url: "https://m.media-amazon.com/images/M/MV5BODMyZjU2NWQtMTI2ZC00Y2ZkLTllYjItNjNiM2Y1NTIyMmIyXkEyXkFqcGdeQXVyNjYzMDA4MTI@._V1_.jpg")
Special.create(title: "Jerry Before Seinfeld", duration_mins: 62, comedian_id: 12, image_url: "https://m.media-amazon.com/images/M/MV5BOTc2N2I0Y2UtOTgyYy00MTU3LTk1YzItZGIwMDcxY2JkMGQzXkEyXkFqcGdeQXVyMjQzNzk2ODk@._V1_.jpg")
